### ISSUE TITLE
use of internal package 

### ISSUE THREAD

**Issue by harkamals** [banzaicloud/productinfo#82]
go build
main.go:43:2: use of internal package github.com/banzaicloud/productinfo/internal/app/productinfo/api not allowed

**Comment by sagikazarmark** [comment]
Can you please paste the result of the following commands here?

```bash
go env GOPATH
echo $PWD
go list .
```

**Comment by harkamals** [comment]
thanks for looking into this..
```
hk:productinfo hk$ go build .
main.go:43:2: use of internal package github.com/banzaicloud/productinfo/internal/app/productinfo/api not allowed
hk:productinfo hk$ go env GOPATH
/Users/hk/go
hk:productinfo hk$ echo $PWD
/Users/hk/Documents/code/go/productinfo/cmd/productinfo
hk:productinfo hk$ go list .
_/Users/hk/Documents/code/go/productinfo/cmd/productinfo
hk:productinfo hk$
```

**Comment by lpuskas** [comment]
@harkamals this is't really a problem related to this project, it's rather about your local environment and Go settings

The easy / recommended way to fix your problem is to check it out to your $GOPATH/src folder (simply run the `go get -d github.com/banzaicloud/productinfo` command) then navigate to the project (`$GOPATH/src/github.com/banzaicloud/productinfo/cmd/productinfo`) and issue the build command.

The other way to go would be to alter your local Go environment which is not recommended

**Comment by lpuskas** [comment]
@harkamals i am closing this, please let us know if you have any other questions.
